import pygame as pg
import os, json

class Map():

    def __init__(self, game, mapDirectory):

        #Default map if the map file can't be loaded to prevent a crash#
        self.gameboard2 = [
            [["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["PLAYER"      ,[2,0]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[False,[2,0]]],["TILE",[True,[1,0]]]],
            [["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]],["TILE",[True,[1,0]]]]
            ]

        #If map exists loads it from the files#
        try:
            with open(os.path.join("Maps",mapDirectory)) as f:
                self.gameboard = json.load(f)
        
		#Else it dumps the gameboard into a text file with the same name as the map#       
        except:
            with open(os.path.join("Maps",mapDirectory), 'w') as f:
                json.dump(self.gameboard, f)

        #Creats constants about the map#
        self.tilesX = len(self.gameboard[0])
        self.tilesY = len(self.gameboard)
        
        self.pixelX = self.tilesX * game.tileSize
        self.pixelY = self.tilesY * game.tileSize


class MapView():

    def __init__(self, x, y):
        #Sets up the game view from map data information#
        self.viewRect = pg.Rect(0,0,x,y)
        self.width = x
        self.height = y

    def createView(self, entity):
        #Function moves the sprite by offset given by the MapView#
        return entity.rect.move(self.viewRect.topleft)

    def update(self, game, player):
        #Changes the postion of the map view based on that of the player (with corner limits)#
        x = -player.rect.x + int(game.screenWidth/2)
        y = -player.rect.y + int(game.screenHeight/2)

        x = min(0, x)
        y = min(0, y)
        x = max(-(self.width - game.screenWidth), x)
        y = max(-(self.height - game.screenHeight), y)
        
        self.viewRect = pg.Rect(x, y, self.width, self.height)
